apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "solar.fullname" . }}
  labels:
    {{- include "solar.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "solar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "solar.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.nodeAffinity.enabled }}  ## jinquan added.
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.nodeAffinity.matchKey }}
                operator: In
                values:
                - {{ .Values.nodeAffinity.matchValue }}
      {{- end }}
      terminationGracePeriodSeconds: 0  ## jinquan added.
      {{- if .Values.podStaticPvc.enabled }}  ## jinquan added.
      volumes:
      - name: datavol
        persistentVolumeClaim:
          claimName: {{ include "solar.fullname" . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "solar.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.podStaticPvc.enabled }}  ## jinquan added.
          volumeMounts:
          - name: datavol
            mountPath: /app/assets   ## echo-server location
          {{- end }}
          ports:
            - name: web    ## jinquan modified.
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.liveProbe.enabled }}  ## jinquan added.
          livenessProbe:
            httpGet:
              path: /api/v1/healthy
              port: web
          {{- end }}
          {{- if .Values.readyProbe.enabled }}  ## jinquan added.
          readinessProbe:
            httpGet:
              path: /api/v1/healthy
              port: web
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
