apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "awsecho.fullname" . }}
  labels:
    {{- include "awsecho.labels" . | nindent 4 }}
    logging: "true"   ## jinquan added.
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "awsecho.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "awsecho.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 0  ## jinquan added.
      {{- if .Values.podStaticPvc.enabled }}  ## jinquan added.
      volumes:
      - name: datavol
        persistentVolumeClaim:
          claimName: {{ include "awsecho.fullname" . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "awsecho.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.podStaticPvc.enabled }}  ## jinquan added.
          volumeMounts:
          - name: datavol
            mountPath: /app/assets   ## echo-server location
          {{- end }}
          ports:
            - name: web
              containerPort: {{ .Values.service.port }}  ## jinquan modified.
              protocol: TCP
          {{- if .Values.liveProbe.enabled }}  ## jinquan added.
          livenessProbe:
            httpGet:
              path: /
              port: web
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
