apiVersion: v1
kind: Service
metadata:
  name: {{ include "awsecho.fullname" . }}
  labels:
    {{- include "awsecho.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1323   ## jinquan modified.
      protocol: TCP
      name: web
  selector:
    {{- include "awsecho.selectorLabels" . | nindent 4 }}
