apiVersion: v1
kind: ConfigMap
metadata:
  name: logetl-cm-{{ .Values.etl.Name }}
  labels:
    {{- include "logetl.labels" . | nindent 4 }}
data:
  logstash.yml: |
    {{- include "logstash.yml" . | nindent 4 }}
  pipelines.yml: |
    {{- include "pipelines.yml" . | nindent 4 }}
  stream-input.conf: |
    {{- include "stream-input.conf" . | nindent 4 }}
  stream-filter.conf: |
{{ .Files.Get "etl/stream-filter.conf" | indent 4 }}
  stream-output.conf: |
    {{- include "stream-output.conf" . | nindent 4 }}
