apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.etl.Name }} #{{ include "logetl.fullname" . }}
  labels:
    {{- include "logetl.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "logetl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "logetl.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "logetl.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: config
        configMap:
          name: logetl-cm-{{ .Values.etl.Name }}
          items:
          - {key: logstash.yml, path: logstash.yml}
          - {key: pipelines.yml, path: pipelines.yml}
      - name: pipeline
        configMap:
          name: logetl-cm-{{ .Values.etl.Name }}
          items:
          - {key: stream-input.conf, path: stream-input.conf}
          - {key: stream-filter.conf, path: stream-filter.conf}
          - {key: stream-output.conf, path: stream-output.conf}
      {{- if .Values.PodCephPvc.enabled }}  ## jinquan added.
      - name: mydata
        persistentVolumeClaim:
          claimName: {{ .Values.etl.Name }}
      {{- end }}
      hostAliases:
          - {ip: "172.24.20.220", hostnames: ["kafka01"]}
          - {ip: "172.24.20.221", hostnames: ["kafka02"]}
          - {ip: "172.24.20.222", hostnames: ["kafka03"]}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: config
            mountPath: /usr/share/logstash/config
          - name: pipeline
            mountPath: /usr/share/logstash/pipeline
          {{- if .Values.PodCephPvc.enabled }}  ## jinquan added.
          - name: mydata
            mountPath: /usr/share/logstash/mydata
          {{- end }}
          ports:
            - containerPort: 5044
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
