apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudbill.fullname" . }}
  labels:
    {{- include "cloudbill.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: aws
    - port: {{ .Values.sidecar.service.port }}
      targetPort: {{ .Values.sidecar.service.port }}
      protocol: TCP
      name: azure
  selector:
    {{- include "cloudbill.selectorLabels" . | nindent 4 }}
