apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jqecho.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.podStaticPvc.capacity }}
  storageClassName: {{ .Values.podStaticPvc.storageclass }}
