apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sqltool.fullname" . }}
  labels:
    {{- include "sqltool.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "config.yaml" . | nindent 4 }}
