{{- if .Values.appConfig.enabled -}}
{{- $fullName := include "canary-demoapp.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "canary-demoapp.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "appconfig.data" . | nindent 4 }}
{{- end }}